const esc = (value) => String(value ?? "-").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]));
const num = (value) => Number(value || 0).toFixed(2);

export const renderInvoiceTemplate = (invoice) => {
  const organizationName = invoice.organization_name || "Logistics Organization";
  const charges = [
    ["Freight Charges", invoice.freight_charge],
    ["Loading Charges", invoice.loading_charge],
    ["Unloading Charges", invoice.unloading_charge],
    ["Fuel Surcharge", invoice.fuel_surcharge],
    ["Insurance Charges", invoice.insurance_charge],
    ["Other Charges", invoice.other_charge],
    ["Vehicle Maintenance", invoice.maintenance_charge]
  ];
  const rows = charges.map(([name, value], index) => `<tr><td>${index + 1}</td><td>${esc(name)}</td><td class="right">&#8377;${num(value)}</td><td class="right">&#8377;${num(value)}</td></tr>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>Invoice ${esc(invoice.invoice_number)}</title><style>
    *{box-sizing:border-box}body{margin:0;background:#fff;color:#111;font-family:Arial,Helvetica,sans-serif;font-size:11px}.page{width:210mm;min-height:297mm;margin:auto;padding:12mm;background:#fff}.top{display:flex;justify-content:space-between;background:#5d0b31;color:#fff;padding:14px 16px}.brand{font-size:22px;font-weight:700;letter-spacing:.4px}.brand small{display:block;font-size:9px;font-weight:400;letter-spacing:1px;margin-top:4px}.title{text-align:right;font-size:24px;font-weight:700}.title small{display:block;font-size:10px;font-weight:400;margin-top:5px}.meta{display:grid;grid-template-columns:1fr 1fr 1fr;border:1px solid #999;border-top:0;padding:9px;gap:10px}.meta h4{margin:0 0 5px;text-transform:uppercase;font-size:9px;color:#5d0b31}.meta p{margin:2px 0}.section{margin-top:13px;border:1px solid #777}.section-title{background:#eee;border-bottom:1px solid #777;padding:5px 7px;font-weight:700;text-transform:uppercase;font-size:9px}.shipment{display:grid;grid-template-columns:repeat(4,1fr);padding:8px;gap:8px}.shipment b{display:block;font-size:9px;color:#555;text-transform:uppercase;margin-bottom:3px}.shipment span{font-weight:600}.charges{width:100%;border-collapse:collapse}.charges th{background:#eee;text-transform:uppercase;font-size:9px}.charges th,.charges td{border:1px solid #888;padding:6px}.right{text-align:right}.totals{margin-left:auto;width:48%;border-collapse:collapse;margin-top:10px}.totals td{padding:5px;border-bottom:1px solid #bbb}.totals tr:last-child{background:#eee;font-size:14px;font-weight:700;border-top:2px solid #5d0b31}.notes{border:1px solid #777;margin-top:20px;padding:8px;min-height:55px}.sign{display:flex;justify-content:space-between;margin-top:42px}.sign span{width:32%;border-top:1px solid #555;padding-top:5px;text-align:center}.footer{text-align:center;color:#666;border-top:1px solid #aaa;margin-top:20px;padding-top:8px;font-size:9px}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}.page{margin:0;width:210mm;min-height:297mm}}
  </style></head><body><main class="page"><header class="top"><div class="brand">${esc(organizationName)}<small>TRANSPORT &amp; LOGISTICS</small></div><div class="title">INVOICE<small>${esc(invoice.invoice_number)}</small></div></header><section class="meta"><div><h4>Bill To</h4><p>Customer ID: ${esc(invoice.customer_id)}</p><p>Shipment Customer</p><p>${esc(invoice.destination)}</p></div><div><h4>Shipping Address</h4><p>${esc(invoice.origin)}</p><p>To ${esc(invoice.destination)}</p></div><div><h4>Invoice Details</h4><p>Invoice Date: ${esc(invoice.invoice_date)}</p><p>Due Date: ${esc(invoice.due_date)}</p><p>Status: ${esc(invoice.status)}</p></div></section><section class="section"><div class="section-title">Shipment Details</div><div class="shipment"><div><b>Shipment Number</b><span>${esc(invoice.shipment_number)}</span></div><div><b>Tracking / LR Number</b><span>${esc(invoice.tracking_number)}</span></div><div><b>Booking Date</b><span>${esc(invoice.booking_date)}</span></div><div><b>Route</b><span>${esc(invoice.origin)} → ${esc(invoice.destination)}</span></div></div></section><section class="section"><div class="section-title">Charge Details</div><table class="charges"><thead><tr><th>#</th><th>Description</th><th>Rate / Amount</th><th>Total Amount</th></tr></thead><tbody>${rows}</tbody></table><table class="totals"><tr><td>Subtotal</td><td class="right">₹${num(invoice.subtotal)}</td></tr><tr><td>Tax</td><td class="right">₹${num(invoice.tax_amount)}</td></tr><tr><td>Discount</td><td class="right">- ₹${num(invoice.discount_amount)}</td></tr><tr><td>Grand Total</td><td class="right">₹${num(invoice.total_amount)}</td></tr></table></section><div class="notes"><b>Notes</b><br>${esc(invoice.notes || "Thank you for your business.")}</div><div class="sign"><span>Prepared By</span><span>Authorized Signature</span><span>Customer Signature</span></div><div class="footer">This is a computer-generated invoice and does not require a physical signature.</div></main></body></html>`;
};
